name: Quality Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: nx run-many --target=test --all --exclude=ts-using-tsc
      - name: Run lint
        run: nx run-many --target=lint --all
